---
- name: Start Azure VM
  hosts: localhost
  tasks:
    - name: Log in to Azure
      shell: az login --service-principal -u {{ secrets.CLIENT_ID }} -p {{ secrets.CLIENT_SECRET }} --tenant {{ secrets.TENANT_ID }}
      register: login_output

    - name: Start the VM
      shell: az vm start --resource-group B2C6A --name backend-backupTest
      when: login_output is succeeded

- name: Setup and start backend application
  hosts: backendtest
  tasks:
    - name: Navigate to directory and start backend application
      shell: python3 Backend_B2A.py
      args:
        chdir: /home/{{ secrets.ADMIN_USERNAME_AZ  }}/B2C6_B2A_Backend
      become: true
