---
- name: Stop Azure VM
  hosts: localhost
  tasks:
    - name: Log in to Azure
      shell: az login --service-principal -u {{ secrets.CLIENT_ID }} -p {{ secrets.CLIENT_SECRET }} --tenant {{ secrets.TENANT_ID }}
      register: login_output

    - name: Stop the VM
      shell: az vm stop --resource-group B2C6A --name backend-backupTest
      when: login_output is succeeded

    - name: Deallocate the VM
      shell: az vm deallocate --resource-group B2C6A --name backend-backupTest
      when: login_output is succeeded
