---
- name: Automate backend setup
  hosts: backendtest
  gather_facts: false

  tasks:
    - name: Check if backend is reachable
      ping:

    - name: Ensure myproject4 directory exists
      become: true
      become_user: {{ secrets.ADMIN_USERNAME_AZ  }}
      file:
        path: /home/{{ secrets.ADMIN_USERNAME_AZ  }}/myproject4
        state: directory

    - name: Clone repository B2C6_B2A_Backend into myproject4 directory
      become: true
      become_user: {{ secrets.ADMIN_USERNAME_AZ  }}
      git:
        repo: https://github.com/ZuydUniversity/B2C6_B2A_Backend.git
        dest: /home/{{ secrets.ADMIN_USERNAME_AZ  }}/myproject4/B2C6_B2A_Backend

    - name: Modify Backend_B2A.py
      become: true
      become_user: {{ secrets.ADMIN_USERNAME_AZ  }}
      lineinfile:
        path: /home/{{ secrets.ADMIN_USERNAME_AZ  }}/myproject4/B2C6_B2A_Backend/Backend_B2A.py
        regexp: '^(.*app.run\(debug=True\))'
        line: "\tapp.run(host='0.0.0.0', port=5000, debug=True)"
